version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  client:
    build: ./client
    ports:
      - 3000:3000
    restart: always
  server:
    build: ./server
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongo
      - rabbit
  notificationServer:
    build: ./notificationServer
    ports:
      - 5001:5001
    restart: always
    depends_on:
      - rabbit
      - server

